DATA CLEANING PROCESS

In [9]:
import pandas as pd
import pymysql  #this will work as an adapter
from sqlalchemy import create_engine

In [10]:
df = pd.read_csv (r"C:\Users\TPA\Desktop\walmart\walmart-10k-sales-datasets\Walmart.csv")

In [6]:
df.shape

(10051, 11)

In [15]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [16]:
df.describe()

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  str
 2   City            10051 non-null  str
 3   category        10051 non-null  str
 4   unit_price      10020 non-null  str
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  str
 7   time            10051 non-null  str
 8   payment_method  10051 non-null  str
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), str(7)
memory usage: 863.9 KB

In [18]:
df.drop_duplicates(inplace = True)

In [19]:
df.dropna(inplace=True)

In [20]:
df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [20]:
df.shape

(9969, 11)

In [21]:
df['unit_price']=df['unit_price'].str.replace('$','').astype(float)

In [22]:
df['total Amount'] = df['unit_price'] * df['quantity']
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total Amount
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17

In [23]:
engine_mysql = create_engine("mysql+pymysql://root:123456789@localhost:3306/walmart_db")
try:
    engine_mysql 
    print("connection sucessuesfully")
except:
    print("access denied")

connection sucessuesfully

In [ ]:

df.to_sql(name='walmart', con=engine_mysql, if_exists='append', index=False)

DatabaseError: Execution failed on sql 'INSERT INTO walmart (invoice_id, "Branch", "City", category, unit_price, quantity, date, time, payment_method, rating, profit_margin, "total Amount") VALUES (:invoice_id, :Branch, :City, :category, :unit_price, :quantity, :date, :time, :payment_method, :rating, :profit_margin, :total_Amount)': (pymysql.err.OperationalError) (1054, "Unknown column 'total Amount' in 'field list'")
[SQL: INSERT INTO walmart (invoice_id, `Branch`, `City`, category, unit_price, quantity, date, time, payment_method, rating, profit_margin, `total Amount`) VALUES (%(invoice_id)s, %(Branch)s, %(City)s, %(category)s, %(unit_price)s, %(quantity)s, %(date)s, %(time)s, %(payment_method)s, %(rating)s, %(profit_margin)s, %(total_Amount)s)]
[parameters: [{'invoice_id': 1, 'Branch': 'WALM003', 'City': 'San Antonio', 'category': 'Health and beauty', 'unit_price': 74.69, 'quantity': 7.0, 'date': '05/01/19', 'time': '13:08:00', 'payment_method': 'Ewallet', 'rating': 9.1, 'profit_margin': 0.48, 'total_Amount': 522.8299999999999}, {'invoice_id': 2, 'Branch': 'WALM048', 'City': 'Harlingen', 'category': 'Electronic accessories', 'unit_price': 15.28, 'quantity': 5.0, 'date': '08/03/19', 'time': '10:29:00', 'payment_method': 'Cash', 'rating': 9.6, 'profit_margin': 0.48, 'total_Amount': 76.39999999999999}, {'invoice_id': 3, 'Branch': 'WALM067', 'City': 'Haltom City', 'category': 'Home and lifestyle', 'unit_price': 46.33, 'quantity': 7.0, 'date': '03/03/19', 'time': '13:23:00', 'payment_method': 'Credit card', 'rating': 7.4, 'profit_margin': 0.33, 'total_Amount': 324.31}, {'invoice_id': 4, 'Branch': 'WALM064', 'City': 'Bedford', 'category': 'Health and beauty', 'unit_price': 58.22, 'quantity': 8.0, 'date': '27/01/19', 'time': '20:33:00', 'payment_method': 'Ewallet', 'rating': 8.4, 'profit_margin': 0.33, 'total_Amount': 465.76}, {'invoice_id': 5, 'Branch': 'WALM013', 'City': 'Irving', 'category': 'Sports and travel', 'unit_price': 86.31, 'quantity': 7.0, 'date': '08/02/19', 'time': '10:37:00', 'payment_method': 'Ewallet', 'rating': 5.3, 'profit_margin': 0.48, 'total_Amount': 604.1700000000001}, {'invoice_id': 6, 'Branch': 'WALM026', 'City': 'Denton', 'category': 'Electronic accessories', 'unit_price': 85.39, 'quantity': 7.0, 'date': '25/03/19', 'time': '18:30:00', 'payment_method': 'Ewallet', 'rating': 4.1, 'profit_margin': 0.48, 'total_Amount': 597.73}, {'invoice_id': 7, 'Branch': 'WALM088', 'City': 'Cleburne', 'category': 'Electronic accessories', 'unit_price': 68.84, 'quantity': 6.0, 'date': '25/02/19', 'time': '14:36:00', 'payment_method': 'Ewallet', 'rating': 5.8, 'profit_margin': 0.33, 'total_Amount': 413.04}, {'invoice_id': 8, 'Branch': 'WALM100', 'City': 'Canyon', 'category': 'Home and lifestyle', 'unit_price': 73.56, 'quantity': 10.0, 'date': '24/02/19', 'time': '11:38:00', 'payment_method': 'Ewallet', 'rating': 8.0, 'profit_margin': 0.18, 'total_Amount': 735.6}  ... displaying 10 of 9969 total bound parameter sets ...  {'invoice_id': 9999, 'Branch': 'WALM032', 'City': 'Tyler', 'category': 'Home and lifestyle', 'unit_price': 79.0, 'quantity': 2.0, 'date': '25/02/21', 'time': '12:25:00', 'payment_method': 'Cash', 'rating': 7.0, 'profit_margin': 0.48, 'total_Amount': 158.0}, {'invoice_id': 10000, 'Branch': 'WALM069', 'City': 'Rockwall', 'category': 'Fashion accessories', 'unit_price': 62.0, 'quantity': 3.0, 'date': '26/09/20', 'time': '9:48:00', 'payment_method': 'Cash', 'rating': 3.0, 'profit_margin': 0.33, 'total_Amount': 186.0}]]
(Background on this error at: https://sqlalche.me/e/21/e3q8)